# Generated by Django 5.0.2 on 2024-04-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_url', models.CharField(blank=True, max_length=30)),
                ('project_name', models.CharField(max_length=30)),
                ('project_description', models.CharField(max_length=300)),
                ('project_technologies', models.CharField(max_length=100)),
                ('project_tools', models.CharField(blank=True, max_length=100)),
                ('project_skills', models.CharField(blank=True, max_length=100)),
                ('project_github', models.CharField(blank=True, max_length=100)),
                ('project_image_path', models.CharField(blank=True, max_length=100)),
                ('project_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.category', verbose_name='Categories')),
            ],
        ),
    ]
