# Generated by Django 5.0.2 on 2024-04-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_project_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_url',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
