# Generated by Django 5.0.2 on 2024-03-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_github_project_project_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image_path',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
